language: ruby
rvm:
  - 2.2.4
  - 2.3.0
  - 2.1.0
  - 2.0.0
compiler:
  - clang
  - gcc-4.8
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
before_install:
  - cc --version
  - gem install bundler -v 1.10.6
