language: ruby
os:
  - linux
  # - osx
before_install:
  - gem install bundler -v 1.10.6
  - bundle install
rvm:
  - 2.5.0
  - 2.4.0
  - 2.3.1
  - 2.2.2
notifications:
  email: false
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gcc-5
script:
  - gem uninstall -x iodine
  - rake install
  - gem uninstall -x iodine
  - CC="gcc-4.9" rake install
  - gem uninstall -x iodine
  - CC="gcc-5" rake install
