language: ruby
compiler:
  - clang
  - gcc
rvm:
  - 2.2.4
  - 2.3.0
  - 2.3.1
  - 2.1.0
  - 2.0.0
sudo: required
dist: trusty
before_install:
  - gem install bundler -v 1.10.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
notifications:
  email: false
